[browser]
gatherUsageStats = false

[server]
runOnSave = true

[theme]
base="light"
font="monospace"
#base="dark"
#primaryColor="#FF7903"
#backgroundColor="#0E1117"
#secondaryBackgroundColor="#31333F"
#textColor="#FAFAFA"

